apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}
spec:
  {{- with .Values.virtualService.hosts }}
  hosts:
    {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.virtualService.gateways }}
  gateways:
    {{- toYaml . | nindent 2 }}
  {{- end }}
  http:
  - name: {{ .Chart.Name }}
    route:
    - destination:
        host: {{ .Chart.Name }}
      weight: 100
