image:
  repository: rwejlgaard/pez.sh
  pullPolicy: IfNotPresent
  tag: ""

replicaCount: 3

service:
  port: 80

deploymentLabels: {}

podAnnotations: {}
labels:
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

resources:
  requests:
    cpu: 50m
    memory: 20Mi
  limits:
    cpu: 100m
    memory: 100Mi

virtualService:
  hosts:
  - pez-sh.london.pez.sh
  - pez-sh.copenhagen.pez.sh
  gateways:
  - istio-system/london-pez-sh
  - istio-system/copenhagen-pez-sh
