image:
  repository: rwejlgaard/pez.sh
  pullPolicy: IfNotPresent
  tag: ""

service:
  port: 80

deploymentLabels: {}

podAnnotations: {}
labels:
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

resources:
  requests:
    cpu: 50m
    memory: 20Mi
  limits:
    cpu: 100m
    memory: 100Mi

rollouts:
  replicas: 1
  canaryService: pez-sh-canary
  stableService: pez-sh-stable
  steps:
  - setWeight: 10
  - pause:
      duration: "5m"
  - setWeight: 20
  - pause:
      duration: "5m"
  - setWeight: 40
  - pause:
      duration: "5m"
  - setWeight: 50
  - pause:
      duration: "5m"

virtualService:
  hosts:
  - pez-sh.london.pez.sh
  - pez-sh.paris.pez.sh
  - pez-sh.copenhagen.pez.sh
  gateways:
  - istio-system/london-pez-sh
  - istio-system/paris-pez-sh
  - istio-system/copenhagen-pez-sh
